In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import convolve

In [2]:
u = np.zeros((5,5), dtype=float)
v = np.zeros((5,5), dtype=float)
r = np.zeros((5,5), dtype=float)
t = np.zeros((5,5), dtype=float)
h = np.zeros((5,5), dtype=float)

In [3]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(r, kernal, mode='same', method='direct')
print("one:")
print(one)
kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(h, kernal, mode='same', method='direct')
print("two:")
print(two)
kernal = np.zeros((5, 5), dtype=float)
# kernal[2,:] = [-1, 3, -3, 1, 0]
kernal[:,2] = [0, 1, -3, 3, -1]
three = convolve(r, kernal, mode='same', method='direct')
print("three:")
print(three)
kernal = np.array([[0, 1, -1],[0, -2, 2],[0, 1, -1]])
four = convolve(h, kernal, mode='same', method='direct')
print("four:")
print(four)
kernal = np.array([[0, 0, 0],[1, -2, 1],[-1, 2, -1]])
five = convolve(t, kernal, mode='same', method='direct')      
print("five:")
print(five)
kernal = np.array([[0, 0, 0],[1, -2, 1],[-1, 2, -1]])
six = convolve(r, kernal, mode='same', method='direct')  
print("six:")
print(six)
kernal = np.zeros((5, 5), dtype=float)
kernal[2, :] = [0, 1, -3, 3, -1]
seven = convolve(h, kernal, mode='same', method='direct')
print("seven:")
print(seven)
u += one + two + three + four + five + six + seven
print("summary:")
print(u)

one:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
two:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
three:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
four:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
five:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
six:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
seven:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
summary:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(h, kernal, mode='same', method='direct')
print("one:")
print(one)
kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(t, kernal, mode='same')
print("two:")
print(two)
kernal = np.zeros((5, 5), dtype=float)
# kernal[2,:] = [0, -1, 3, -3, 1]
kernal[:,2] = [1, -3, 3, -1, 0]
three = convolve(h, kernal, mode='same', method='direct')
print("three:")
print(three)
kernal = np.array([[1, -2, 1],[-1, 2, -1],[0, 0, 0]])
four = convolve(h, kernal, mode='same', method='direct')
print("four:")
print(four)
kernal = np.array([[1, -1, 0],[-2, 2, 0],[1, -1, 0]])
five = convolve(r, kernal, mode='same', method='direct')   
print("five:")
print(five)
kernal = np.array([[1, -1, 0],[-2, 2, 0],[1, -1, 0]])
six = convolve(t, kernal, mode='same', method='direct')
print("six:")
print(six)
kernal = np.zeros((5, 5), dtype=float)
# kernal[:,2] = [0, -1, 3, -3, 1]
kernal[2,:] = [1, -3, 3, -1, 0]
seven = convolve(t, kernal, mode='same', method='direct')
print("seven:")
print(seven)
v += one + two + three + four + five + six + seven
print("summary:")
print(v)

one:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
two:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
three:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
four:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
five:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
six:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
seven:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
summary:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(u, kernal, mode='same', method='direct')
print("one:")
print(one)

kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(v, kernal, mode='same', method='direct')
print("two:")
print(two)

kernal = np.zeros((5,5), dtype=float)
# kernal[2,:] = [0, -1, 3, -3, 1]
kernal[:,2] = [1, -3, 3, -1, 0]
three = convolve(u, kernal, mode='same', method='direct')
print("three:")
print(three)

kernal = np.array([[0, 1, -1],[0, -2, 2],[0, 1, -1]])
four = convolve(v, kernal, mode='same', method='direct')  
print("four:")
print(four)

kernal = np.array([[1, -2, 1],[-1, 2, -1],[0, 0, 0]])
five = convolve(u, kernal, mode='same', method='direct')  
print("five:")
print(five)

kernal = np.zeros((5,5), dtype=float)
kernal[2, :] = [0, 1, -3, 3, -1]
six = convolve(v, kernal, mode='same', method='direct')
print("six:")
print(six)

r += one + two + three + four + five + six
print("summary:")
print(r)

one:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
two:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
three:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
four:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
five:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
six:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
summary:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(u, kernal, mode='same', method='direct')
print("one:")
print(one)

kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(v, kernal, mode='same', method='direct')
print("two:")
print(two)

kernal = np.zeros((5,5), dtype=float)
# kernal[2,:] = [0, -1, 3, -3, 1]
kernal[:,2] = [1, -3, 3, -1, 0]
three = convolve(u, kernal, mode='same', method='direct')
print("three:")
print(three)

kernal = np.array([[0, 1, -1],[0, -2, 2],[0, 1, -1]])
four = convolve(v, kernal, mode='same', method='direct')  
print("four:")
print(four)

kernal = np.array([[1, -2, 1],[-1, 2, -1],[0, 0, 0]])
five = convolve(u, kernal, mode='same', method='direct') 
print("five:")
print(five)

kernal = np.zeros((5,5), dtype=float)
# kernal[:,2] = [-1, 3, -3, 1, 0]
kernal[2, :] = [0, 1, -3, 3, -1]
six = convolve(v, kernal, mode='same', method='direct')
print("six:")
print(six)

t += one + two + three + four + five + six
print("summary:")
print(t)

one:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
two:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
three:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
four:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
five:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
six:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
summary:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(v, kernal, mode='same', method='direct')
print("one:")
print(one)

kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(u, kernal, mode='same', method='direct')
print("two:")
print(two)

kernal = np.zeros((5,5), dtype=float)
# kernal[2,:] = [-1, 3, -3, 1, 0]
kernal[:,2] = [0, 1, -3, 3, -1]
three = convolve(v, kernal, mode='same', method='direct')        
print("three:")
print(three)

kernal = np.array([[1, -1, 0],[-2, 2, 0],[1, -1, 0]])
four = convolve(u, kernal, mode='same', method='direct')  
print("four:")
print(four)

kernal = np.array([[0,0,0],[1, -2, 1],[-1, 2, -1]])
five = convolve(v, kernal, mode='same', method='direct')  
print("five:")
print(five)

kernal = np.zeros((5,5), dtype=float)
kernal[2, :] = [1, -3, 3, -1, 0]
six = convolve(u, kernal, mode='same', method='direct')
print("six:")
print(six)

h += one + two + three + four + five + six
print("summary:")
print(h)

one:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
two:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
three:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
four:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
five:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
six:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
summary:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
u[2,2] += -1
print(u)
print(v)
print(r)
print(t)
print(h)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(r, kernal, mode='same', method='direct')
print("one:")
print(one)
kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(h, kernal, mode='same', method='direct')
print("two:")
print(two)
kernal = np.zeros((5, 5), dtype=float)
# kernal[2,:] = [-1, 3, -3, 1, 0]
kernal[:,2] = [0, 1, -3, 3, -1]
three = convolve(r, kernal, mode='same', method='direct')
print("three:")
print(three)
kernal = np.array([[0, 1, -1],[0, -2, 2],[0, 1, -1]])
four = convolve(h, kernal, mode='same', method='direct')
print("four:")
print(four)
kernal = np.array([[0, 0, 0],[1, -2, 1],[-1, 2, -1]])
five = convolve(t, kernal, mode='same', method='direct')      
print("five:")
print(five)
kernal = np.array([[0, 0, 0],[1, -2, 1],[-1, 2, -1]])
six = convolve(r, kernal, mode='same', method='direct')  
print("six:")
print(six)
kernal = np.zeros((5, 5), dtype=float)
kernal[2, :] = [0, 1, -3, 3, -1]
seven = convolve(h, kernal, mode='same', method='direct')
print("seven:")
print(seven)
u += one + two + three + four + five + six + seven
print("summary:")
print(u)

one:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
two:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
three:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
four:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
five:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
six:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
seven:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
summary:
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [10]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(h, kernal, mode='same', method='direct')
print("one:")
print(one)
kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(t, kernal, mode='same')
print("two:")
print(two)
kernal = np.zeros((5, 5), dtype=float)
# kernal[2,:] = [0, -1, 3, -3, 1]
kernal[:,2] = [1, -3, 3, -1, 0]
three = convolve(h, kernal, mode='same', method='direct')
print("three:")
print(three)
kernal = np.array([[1, -2, 1],[-1, 2, -1],[0, 0, 0]])
four = convolve(h, kernal, mode='same', method='direct')
print("four:")
print(four)
kernal = np.array([[1, -1, 0],[-2, 2, 0],[1, -1, 0]])
five = convolve(r, kernal, mode='same', method='direct')   
print("five:")
print(five)
kernal = np.array([[1, -1, 0],[-2, 2, 0],[1, -1, 0]])
six = convolve(t, kernal, mode='same', method='direct')
print("six:")
print(six)
kernal = np.zeros((5, 5), dtype=float)
# kernal[:,2] = [0, -1, 3, -3, 1]
kernal[2,:] = [1, -3, 3, -1, 0]
seven = convolve(t, kernal, mode='same', method='direct')
print("seven:")
print(seven)
v += one + two + three + four + five + six + seven
print("summary:")
print(v)

one:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
two:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
three:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
four:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
five:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
six:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
seven:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
summary:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(u, kernal, mode='same', method='direct')
print("one:")
print(one)

kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(v, kernal, mode='same', method='direct')
print("two:")
print(two)

kernal = np.zeros((5,5), dtype=float)
# kernal[2,:] = [0, -1, 3, -3, 1]
kernal[:,2] = [1, -3, 3, -1, 0]
three = convolve(u, kernal, mode='same', method='direct')
print("three:")
print(three)

kernal = np.array([[0, 1, -1],[0, -2, 2],[0, 1, -1]])
four = convolve(v, kernal, mode='same', method='direct')  
print("four:")
print(four)

kernal = np.array([[1, -2, 1],[-1, 2, -1],[0, 0, 0]])
five = convolve(u, kernal, mode='same', method='direct')  
print("five:")
print(five)

kernal = np.zeros((5,5), dtype=float)
kernal[2, :] = [0, 1, -3, 3, -1]
six = convolve(v, kernal, mode='same', method='direct')
print("six:")
print(six)

r += one + two + three + four + five + six
print("summary:")
print(r)

one:
[[ 0.  0. -1.  0.  0.]
 [ 0.  0. -2.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.]
 [ 0.  0.  1.  0.  0.]]
two:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
three:
[[ 0.  0. -1.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0. -3.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
four:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
five:
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
six:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
summary:
[[ 0.  0. -2.  0.  0.]
 [ 0. -1.  3. -1.  0.]
 [ 0.  1. -5.  1.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  1.  0.  0.]]


In [12]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(u, kernal, mode='same', method='direct')
print("one:")
print(one)

kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(v, kernal, mode='same', method='direct')
print("two:")
print(two)

kernal = np.zeros((5,5), dtype=float)
# kernal[2,:] = [0, -1, 3, -3, 1]
kernal[:,2] = [1, -3, 3, -1, 0]
three = convolve(u, kernal, mode='same', method='direct')
print("three:")
print(three)

kernal = np.array([[0, 1, -1],[0, -2, 2],[0, 1, -1]])
four = convolve(v, kernal, mode='same', method='direct')  
print("four:")
print(four)

kernal = np.array([[1, -2, 1],[-1, 2, -1],[0, 0, 0]])
five = convolve(u, kernal, mode='same', method='direct') 
print("five:")
print(five)

kernal = np.zeros((5,5), dtype=float)
# kernal[:,2] = [-1, 3, -3, 1, 0]
kernal[2, :] = [0, 1, -3, 3, -1]
six = convolve(v, kernal, mode='same', method='direct')
print("six:")
print(six)

t += one + two + three + four + five + six
print("summary:")
print(t)

one:
[[ 0.  0. -1.  0.  0.]
 [ 0.  0. -2.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.]
 [ 0.  0.  1.  0.  0.]]
two:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
three:
[[ 0.  0. -1.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0. -3.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
four:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
five:
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
six:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
summary:
[[ 0.  0. -2.  0.  0.]
 [ 0. -1.  3. -1.  0.]
 [ 0.  1. -5.  1.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  1.  0.  0.]]


In [13]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(v, kernal, mode='same', method='direct')
print("one:")
print(one)

kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(u, kernal, mode='same', method='direct')
print("two:")
print(two)

kernal = np.zeros((5,5), dtype=float)
# kernal[2,:] = [-1, 3, -3, 1, 0]
kernal[:,2] = [0, 1, -3, 3, -1]
three = convolve(v, kernal, mode='same', method='direct')        
print("three:")
print(three)

kernal = np.array([[1, -1, 0],[-2, 2, 0],[1, -1, 0]])
four = convolve(u, kernal, mode='same', method='direct')  
print("four:")
print(four)

kernal = np.array([[0,0,0],[1, -2, 1],[-1, 2, -1]])
five = convolve(v, kernal, mode='same', method='direct')  
print("five:")
print(five)

kernal = np.zeros((5,5), dtype=float)
kernal[2, :] = [1, -3, 3, -1, 0]
six = convolve(u, kernal, mode='same', method='direct')
print("six:")
print(six)

h += one + two + three + four + five + six
print("summary:")
print(h)

one:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
two:
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1. -2.  0.  1.  2.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
three:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
four:
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  2. -2.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
five:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
six:
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  3. -3.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
summary:
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [-2.  3. -5.  2.  2.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [14]:
u[2,2] += -2
print(u)
print(v)
print(r)
print(t)
print(h)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -3.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 0.  0. -2.  0.  0.]
 [ 0. -1.  3. -1.  0.]
 [ 0.  1. -5.  1.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  1.  0.  0.]]
[[ 0.  0. -2.  0.  0.]
 [ 0. -1.  3. -1.  0.]
 [ 0.  1. -5.  1.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  1.  0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [-2.  3. -5.  2.  2.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [15]:
kernal = np.array([[0,0,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,-2,0,0],[0,0,-1,0,0]])
one = convolve(r, kernal, mode='same', method='direct')
print("one:")
print(one)
kernal = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-1,-2],[0,0,0,0,0],[0,0,0,0,0],])
two = convolve(h, kernal, mode='same', method='direct')
print("two:")
print(two)
kernal = np.zeros((5, 5), dtype=float)
# kernal[2,:] = [-1, 3, -3, 1, 0]
kernal[:,2] = [0, 1, -3, 3, -1]
three = convolve(r, kernal, mode='same', method='direct')
print("three:")
print(three)
kernal = np.array([[0, 1, -1],[0, -2, 2],[0, 1, -1]])
four = convolve(h, kernal, mode='same', method='direct')
print("four:")
print(four)
kernal = np.array([[0, 0, 0],[1, -2, 1],[-1, 2, -1]])
five = convolve(t, kernal, mode='same', method='direct')      
print("five:")
print(five)
kernal = np.array([[0, 0, 0],[1, -2, 1],[-1, 2, -1]])
six = convolve(r, kernal, mode='same', method='direct')  
print("six:")
print(six)
kernal = np.zeros((5, 5), dtype=float)
kernal[2, :] = [0, 1, -3, 3, -1]
seven = convolve(h, kernal, mode='same', method='direct')
print("seven:")
print(seven)
u += one + two + three + four + five + six + seven
print("summary:")
print(u)

one:
[[ 0. -1.  1. -1.  0.]
 [ 0.  2. -3.  2.  0.]
 [ 0.  2.  3.  2.  0.]
 [ 0. -1.  9. -1.  0.]
 [ 0. -1. -1. -1.  0.]]
two:
[[ 0.  0.  0.  0.  0.]
 [-1.  2.  1.  1. -2.]
 [ 1. -6.  7.  3.  8.]
 [-1.  2.  1.  1. -2.]
 [ 0.  0.  0.  0.  0.]]
three:
[[  0.  -1.   9.  -1.   0.]
 [  0.   4. -20.   4.   0.]
 [  0.  -6.  29.  -6.   0.]
 [  0.   4. -26.   4.   0.]
 [  0.  -1.  11.  -1.   0.]]
four:
[[  0.  -1.   2.  -1.   0.]
 [ -2.   7. -12.   9.   0.]
 [  4. -12.  20. -16.   0.]
 [ -2.   7. -12.   9.   0.]
 [  0.  -1.   2.  -1.   0.]]
five:
[[  0.  -2.   4.  -2.   0.]
 [ -1.   7. -12.   7.  -1.]
 [  2. -12.  20. -12.   2.]
 [ -1.  10. -18.  10.  -1.]
 [  0.  -2.   4.  -2.   0.]]
six:
[[  0.  -2.   4.  -2.   0.]
 [ -1.   7. -12.   7.  -1.]
 [  2. -12.  20. -12.   2.]
 [ -1.  10. -18.  10.  -1.]
 [  0.  -2.   4.  -2.   0.]]
seven:
[[  0.   0.   0.   0.   0.]
 [ -1.   4.  -6.   4.  -1.]
 [  9. -20.  28. -22.   5.]
 [ -1.   4.  -6.   4.  -1.]
 [  0.   0.   0.   0.   0.]]
summary:
[[  0.  -7.  

In [28]:
def update_u(u,v,r,t,h):
    kernal_1 = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-2,-1],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_2 = kernal_1.T
    kernal_3 = np.array([[0,0,0,0,0],[0,0,0,0,0],[0,1,-3,3,-1],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_4 = np.array([[0,0,0],[1,-2,1],[-1,2,-1]])
    kernal_5 = np.array([[0,1,-1],[0,-2,2],[0,1,-1]])
    kernal_6 = kernal_5
    kernal_7 = kernal_3.T
    output = convolve(r, kernal_1, mode='same', method='direct') + convolve(h, kernal_2, mode='same', method='direct') + \
                convolve(r, kernal_3, mode='same', method='direct') + convolve(h, kernal_4, mode='same', method='direct') + \
                    convolve(t, kernal_5, mode='same', method='direct') + convolve(r, kernal_6, mode='same', method='direct') + \
                       convolve(h, kernal_7, mode='same', method='direct') 
    return output

def update_v(u,v,r,t,h):
    kernal_1 = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-2,-1],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_2 = kernal_1.T
    kernal_3 = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,-3,3,-1,0],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_4 = np.array([[1,-1,0],[-2,2,0],[1,-1,0]])
    kernal_5 = np.array([[1,-2,1],[-1,2,-1],[0,0,0]])
    kernal_6 = kernal_5
    kernal_7 = kernal_3.T
    output = convolve(h, kernal_1, mode='same', method='direct') + convolve(t, kernal_2, mode='same', method='direct') + \
                convolve(h, kernal_3, mode='same', method='direct') + convolve(h, kernal_4, mode='same', method='direct') + \
                    convolve(r, kernal_5, mode='same', method='direct') + convolve(t, kernal_6, mode='same', method='direct') + \
                       convolve(t, kernal_7, mode='same', method='direct') 
    return output

def update_r(u,v,r,t,h):
    kernal_1 = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-2,-1],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_2 = kernal_1.T
    kernal_3 = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,-3,3,-1,0],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_4 = np.array([[0,0,0],[1,-2,1],[-1,2,-1]])
    kernal_5 = np.array([[1,-1,0],[-2,2,0],[1,-1,0]])
    kernal_6 = kernal_3.T
    output = convolve(u, kernal_1, mode='same', method='direct') + convolve(v, kernal_2, mode='same', method='direct') + \
                convolve(u, kernal_3, mode='same', method='direct') + convolve(v, kernal_4, mode='same', method='direct') + \
                    convolve(u, kernal_5, mode='same', method='direct') + convolve(v, kernal_6, mode='same', method='direct')
    return output

def update_t(u,v,r,t,h):
    kernal_1 = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-2,-1],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_2 = kernal_1.T
    kernal_3 = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,-3,3,-1,0],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_4 = np.array([[0,0,0],[1,-2,1],[-1,2,-1]])
    kernal_5 = np.array([[1,-1,0],[-2,2,0],[1,-1,0]])
    kernal_6 = kernal_3.T
    output = convolve(u, kernal_1, mode='same', method='direct') + convolve(v, kernal_2, mode='same', method='direct') + \
                convolve(u, kernal_3, mode='same', method='direct') + convolve(v, kernal_4, mode='same', method='direct') + \
                    convolve(u, kernal_5, mode='same', method='direct') + convolve(v, kernal_6, mode='same', method='direct')
    return output

def update_h(u,v,r,t,h):
    kernal_1 = np.array([[0,0,0,0,0],[0,0,0,0,0],[1,2,0,-2,-1],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_2 = kernal_1.T
    kernal_3 = np.array([[0,0,0,0,0],[0,0,0,0,0],[0,1,-3,3,-1],[0,0,0,0,0],[0,0,0,0,0]])
    kernal_4 = np.array([[1,-2,1],[-1,2,-1],[0,0,0]])
    kernal_5 = np.array([[0,1,-1],[0,-2,2],[0,1,-1]])
    kernal_6 = kernal_3.T
    output = convolve(v, kernal_1, mode='same', method='direct') + convolve(u, kernal_2, mode='same', method='direct') + \
                convolve(v, kernal_3, mode='same', method='direct') + convolve(u, kernal_4, mode='same', method='direct') + \
                    convolve(v, kernal_5, mode='same', method='direct') + convolve(u, kernal_6, mode='same', method='direct')
    return output

In [36]:
u = np.zeros((11,11), dtype=float)
v = np.zeros((11,11), dtype=float)
r = np.zeros((11,11), dtype=float)
t = np.zeros((11,11), dtype=float)
h = np.zeros((11,11), dtype=float)

In [40]:
u += update_u(u,v,r,t,h)
v += update_v(u,v,r,t,h)
r += update_r(u,v,r,t,h)
t += update_t(u,v,r,t,h)
h += update_h(u,v,r,t,h)
u[5,5] += -2

print(u)
print(v)
print(r)
print(t)
print(h)

[[ 0.0000e+00  0.0000e+00 -2.2000e+01 -1.7400e+02  4.7000e+02 -5.8600e+02
   5.1800e+02 -1.7400e+02 -3.8000e+01  0.0000e+00  0.0000e+00]
 [ 0.0000e+00 -6.6000e+01 -1.9400e+02  7.2400e+02 -1.4140e+03  2.2700e+03
  -1.5280e+03  7.5600e+02 -1.5600e+02 -8.2000e+01  0.0000e+00]
 [-4.4000e+01 -1.0000e+02  1.7600e+02 -3.4600e+02  6.8000e+02 -8.3200e+02
   7.9400e+02 -3.9400e+02  1.3800e+02 -7.6000e+01 -4.4000e+01]
 [-9.2000e+01 -1.8000e+01  1.4460e+03 -4.9500e+03  8.9560e+03 -1.0886e+04
   8.9880e+03 -5.2080e+03  1.4920e+03  1.2000e+02 -1.2600e+02]
 [ 3.2000e+02  7.1800e+02 -5.7140e+03  1.6980e+04 -2.9770e+04  3.5928e+04
  -3.0442e+04  1.7952e+04 -5.7780e+03  2.2600e+02  5.2000e+02]
 [-3.0400e+02 -1.2020e+03  9.0160e+03 -2.4480e+04  4.1624e+04 -5.1376e+04
   4.2760e+04 -2.5864e+04  9.1000e+03 -5.0400e+02 -6.5600e+02]
 [ 2.7600e+02  7.6400e+02 -5.2380e+03  1.4568e+04 -2.4474e+04  3.0080e+04
  -2.4990e+04  1.5516e+04 -5.3540e+03  2.8400e+02  4.7600e+02]
 [-7.6000e+01 -1.2600e+02  1.1260e+03 -2.